---
- block:
  - name: 'packages : update apt cache'
    apt:
      update_cache: yes

  - name: 'packages : install common packages'
    apt:
      name:
        - build-essential
        - curl
        - dircolors
        - git
        - libcurl4-openssl-dev
        - nano
        - nmap
        - openvpn
        - python
        - python-pip
        - python-setuptools
        - python3
        - python3-pip
        - python3-setuptools
        - socat
        - tar
        - ufw
        - unzip
        - vim
        - zip
        - zsh

  - name: 'packages : install common Python modules'
    pip:
      name: pyopenssl
  tags:
    - common
    - packages
